services:
    _defaults:
        autowire: true
        autoconfigure: true

    EonX\EasyAwsCredentialsFinder\:
        resource: '../../../../../src'
        exclude:
            - '../../../../../src/Bridge/*'
            - '../../../../../src/AwsCredentials.php'
